spring:
  application:
    name: api-gateway

server:
  port: 8082
  
zuul:
  routes:
    greetingsClient:
      serviceId: greetings-client
      path: /lets/*

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
