spring:
  application:
    name: customer-service
  kafka:
    bootstrap-servers: [ localhost:9001, localhost:9002, localhost:9003 ]

configuration:
  projectName: 'Spring Cloud4'

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
